create table customer (customerID smallSerial not null, name varchar(35) not null, age int4 not null, roomNum int4 not null, phone char(10) not null, primary key (customerID));
create table animator (empID smallSerial not null, name varchar(35) not null, phoneNum char(10) not null, expArea varchar(255) not null, primary key (empID));
create table equip_person (empID int not null, ssn char(9) not null unique, name varchar(35) not null, surname varchar(35) not null, phoneNum char(10) not null, primary key (empID));
create table appointment (customerID int not null, activityID int not null, animatorID int not null, dateHour timestamp not null, primary key (customerID, activityID, animatorID));
create table massActivity (activityID int not null, activityType varchar(35) not null, capacity varchar(10) not null, primary key (activityID));
create table individualActivity (activityID int not null, age int4 not null, primary key (activityID));
create table emergencyInformation (activityID int not null, phoneNum char(255) not null, LockerNum int4 not null, primary key (activityID));
create table equipment (eSSN char(9) not null, name varchar(35) not null, purpose varchar(255) not null, primary key (eSSN));
create table activity (activityID smallSerial not null, name varchar(35) not null, link varchar(255) not null, "date" date not null, hour time(7) not null, animatorID int not null, primary key (activityID));
create table activityHistory (activityID int not null, phoneNum char(10) not null, lockerNum int4 not null, primary key (activityID));
create table customerPassword (customerID int not null, password varchar(16) not null, primary key (customerID));
create table animatorPassword (animatorID int not null, password varchar(16) not null, primary key (animatorID));
alter table appointment add constraint FKappointmen778166 foreign key (customerID) references customer (customerID);
alter table appointment add constraint FKappointmen277960 foreign key (activityID) references activity (activityID);
alter table equip_person add constraint FKequip_pers942931 foreign key (empID) references animator (empID);
alter table massActivity add constraint FKmassActivi392623 foreign key (activityID) references activity (activityID);
alter table emergencyInformation add constraint FKemergencyI893669 foreign key (activityID) references activity (activityID);
alter table individualActivity add constraint FKindividual872204 foreign key (activityID) references activity (activityID);
alter table appointment add constraint FKappointmen316376 foreign key (animatorID) references animator (empID);
alter table animatorPassword add constraint FKanimatorPa507510 foreign key (animatorID) references animator (empID);
alter table customerPassword add constraint FKcustomerPa912509 foreign key (customerID) references customer (customerID);
alter table equipment add constraint FKequipment557973 foreign key (eSSN) references equip_person (ssn);
alter table activity add constraint FKactivity288221 foreign key (animatorID) references animator (empID);
